from . import common
from . import test_demo
from . import test_availability
from . import test_wedding_pair
from . import test_pricing
from . import test_payments
from . import test_lifecycle
from . import test_reports
from . import test_rules
from . import test_security
from . import test_migration
from . import test_menus
